### ISSUE TITLE
Calamari launch checklist for kusama network

### ISSUE THREAD

**Issue by stechu** [Manta-Network/pallet-manta-pay#92]
- [ ] Chainspec 
    - [x] multi-sig accounts configuration (Shumo)
    - [x] Chain-spec as json (Jamie)
- [ ] Genesis state/wasm for crowdloan(Once we submit them to kusama, it's hard to change)
    - [ ] genesis state
    - [ ] genesis wasm
- [ ] Docker-image (good to have)  
- [ ] Testing (test block producing time)
   - [x] multisig (Shumo, Jamie)
   - [x] runtime upgrade (Georgi)
   - [x] collator/archieval/full node settings (5 collators, 1 full node as tx end point, 1 archival node for subscan).
   - [ ] kick and add collators  and check why Acala modify collator-selection
- [x] Subscan integration (Kevin)  
   - [x] dry run     
- [ ] Internal Code Audit (TBD?)
- [ ] Deployment settings (Rob, Shumo, Jamie, Georgi)
